import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useMoralis, useWeb3Contract } from "react-moralis";
import { abi } from "../constants/abi";
import { contractAddress } from "../constants/contract-address";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [hasMetamask, setHasMetamask] = useState(false);
  const { enableWeb3, isWeb3Enabled } = useMoralis();

  const { data, error, runContractFunction, isFetching, isLoading } =
    useWeb3Contract({
      abi: abi,
      contractAddress,
      functionName: "store",
      params: {
        _favoriteNumber: 42,
      },
    });

  useEffect(() => {
    if (typeof window.ethereum !== "undefined") {
      setHasMetamask(true);
    }
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          {hasMetamask ? (
            isWeb3Enabled ? (
              "Connected! "
            ) : (
              <button onClick={() => enableWeb3()}>Connect</button>
            )
          ) : (
            "Please install metamask"
          )}

          {isWeb3Enabled ? (
            <button onClick={() => runContractFunction()}>Execute</button>
          ) : (
            ""
          )}
        </div>
      </main>
    </>
  );
}
